name: "Rotate MantisHub Version"
description: "An action to rename upcoming release to specify name, mark it as released and create a new upcoming release."

inputs:
  url:
    description: "Base URL of the MantisHub API"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
  project:
    description: "Project Name"
    required: true
  placeholder-name:
    description: "Placeholder name for upcoming release e.g vNext"
    required: true
  release-name:
    description: "Name of released version e.g 1.0.0"
    required: true
  next-release-in-days:
    description: "Next release in days"
    required: true
outputs:
  version-id:
    description: "The ID of the created version."
runs:
  using: "node20"
  main: "index.js"
